# 数据源配置
spring:
  datasource:
    name: newbee-mall-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newbee_mall_plus_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
    hikari:
      pool-name: hikariCP
      minimum-idle: 100
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password:
    databaseIndex: 3
    expire: 400
    maxTotal: 50000
    jedis:
      pool:
        max-active: 50
        max-idle: 100
        min-idle: 10
        max-wait: 2000